### ISSUE TITLE
Running NPM Scripts via GUI does not work if VSCODE is opened via context menu.

### ISSUE THREAD

**Issue by IngoVals** [harry-cpp/code-nautilus#21]
Strange bug for sure.

Running it via GUI

```
> Executing task: npm run build <

/bin/bash: npm: command not found
The terminal process "bash '-c', 'npm run build'" failed to launch (exit code: 127).

Terminal will be reused by tasks, press any key to close it.
```

But with same instance using internal terminal

```
$ npm run build

> bundling_test@1.0.0 build
> webpack --mode production

asset main.js 20 bytes [compared for emit] [minimized] (name: main)
./src/index.js 21 bytes [built] [code generated]
webpack 5.52.0 compiled successfully in 239 ms
```

I have all default settings for integrated terminal for linux.

**Comment by harry-cpp** [comment]
Check your PATH variable between the two sessions (echo $PATH), its probably not set properly.

Also the error has nothing to do with this extension, so closing the issue, but feel free to continue the discussion.

**Comment by pinich** [comment]
I'm having a similar error on a linux machine, on windows with the same profile it works fine.
This happens only when running the task from package.json/scripts
