### ISSUE TITLE
How to specify python path?

### ISSUE THREAD

**Issue by liblaf** [harry-cpp/code-nautilus#29]
It's not a problem with the project.

I am using Ubuntu Desktop 22.04.1 LTS with GNOME 42.4.

I have multiple versions of python in my `$PATH`. However, the system default python, which is `/usr/bin/python3`, is not the first `python3` in `$PATH`. So when I start `nautilus`, the extension fails due to missing module `gi`.

How can I tell `python-nautilus` to use `/usr/bin/python3`?

**Comment by anujdatar** [comment]
you could add a shebang in the `code-nautilus.py` file (at the very top)

```python
#!/usr/bin/python3
```
